cognito_domain_name    = "media-intelligence-domain-test"
email                  = "aesheriff30@gmail.com"
s3_bucket              = "media-convert-input-bucket-11132024"
destination_bucket     = "media-convert-output-bucket-11132024"
es_domain_name         = "aprendiendoaws-ml-mi-domain"
dynamodb_table_name    = "aprendiendoaws-ml-mi-jobs"
stage_name             = "Prod"
osc_dictionary         = "osc_files/dictionary.json"
